import { Divider, Flex, Heading, Stack, Text } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <Flex>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Stack spacing={4} direction={"column"} align="center" justify="center" w="100%" minH="100vh">
        <Heading>
          Pedro dos Santos Cruz
        </Heading>
        <Stack align="center" justify={"center"} direction={"row"} spacing={2} >
          <Text>
            github.com/pscruzzz
          </Text>
          <Divider h="25px" w="1px" bg={"gray.300"} orientation='vertical' />
          <Text>
            pedro.scruz@icloud.com
          </Text>
          <Divider h="25px" w="1px" bg={"gray.300"} orientation='vertical' />
          <Text>
            linkedin.com/in/pedrosantoscruz/
          </Text>
        </Stack>
      </Stack>
    </Flex >
  )
}
